### ISSUE TITLE
content element + text & media (video) + ie11 - wrong height and flicker outside the container

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_slider#9] opened 2020-05-19 13:02 UTC
Hi,

I noticed that there is an issue if you want to use the slider as content element slider with an text & media element which has only a video file (for a video slider). This problem is only in IE11 and I currently don't know if it is a tiny-slider issue or another thing.

What I did was:
1. create a slider with 5 or more "text & media" content elements
2. add to each content element a mp4 videofile
3. in options: slides to scroll = 1 and add an option in the json for responsiveness:
`"responsive": {"640": {"edgePadding": 20,"gutter": 20,"items": 2},"992": {"edgePadding": 30,"items": 3},"1200": {"edgePadding": 40,"items": 4}},`

In Chrome, Edge and Firefox all is fine but IE11 has some problems.

First, I see 5 or more slides and not only 4.
The Second problem is the wrong height of the slides. It seems like that the slides are not correctly calculated and they have a 100% width and overlap each other.

If I activate the loop option in the slider options, I see even more slides on the left and right and if I scroll using the arrow buttons the slides flicker.

I also use the hh_video_extender extension.

Can someone reproduce some of the mentioned problems in IE11?

![grafik](https://user-images.githubusercontent.com/33951787/82332177-60464580-99e5-11ea-9164-b5a331c7f2ea.png)

**Comment by Teisi** [comment] 2020-05-25 14:17
No sry can't reproduce this with Win 10 and IE 11.836.18362.0
I have a height issue if for example class="ce-textpic..." is set to display: flex.
(You have to set the responsive CSS for the HTML video-tag, like described here: https://blog.kulturbanause.de/2011/09/flexible-videos-im-responsive-webdesign/#chapter2)

Well I think this is not an issue of this extension, it looks more like a CSS problem to me.
So i close this. If anyone disagrees with that simply comment.

**Closed as completed by Teisi** 2020-05-25 14:17 UTC
